name: Deploy Storybook

on:
  push:
    branches:
      - master

jobs:
  deploy-storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Ensure that git uses your token with write access to the repo
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare repository
        # Fetch full git history and tags
        run: git fetch --unshallow --tags

      - name: Use Node.js 12.x
        uses: actions/setup-node@v2.1.5
        with:
          node-version: '12'

      - name: ðŸ’¸ Cache node modules
        uses: actions/cache@v3.2.2
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm 
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-

      - name: ðŸ“¦ Install deps
        run: npm ci

      - name: ðŸ›³ Deploy Storybook
        run: npx -p @storybook/storybook-deployer storybook-to-ghpages --ci
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GH_TOKEN }}
